"""Add timestamp to VideoClip

Revision ID: 13f903762133
Revises: 89b916d46f6c
Create Date: 2024-11-04 07:36:10.667967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13f903762133'
down_revision = '89b916d46f6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_clips', sa.Column('timestamp', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_clips', 'timestamp')
    # ### end Alembic commands ###
