"""Add timestamp to VideoClip

Revision ID: 1cb80f09f95d
Revises: 13f903762133
Create Date: 2024-11-04 07:47:13.150426

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1cb80f09f95d'
down_revision = '13f903762133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_clips', sa.Column('eventname', sa.String(length=50), nullable=False))
    op.drop_column('video_clips', 'event_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_clips', sa.Column('event_name', mysql.VARCHAR(length=50), nullable=False))
    op.drop_column('video_clips', 'eventname')
    # ### end Alembic commands ###
