"""empty message

Revision ID: 464d225f3785
Revises: 
Create Date: 2024-11-04 19:01:18.751971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464d225f3785'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
