"""Initial migration

Revision ID: 46991c73149b
Revises: 
Create Date: 2024-06-20 13:21:32.527807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46991c73149b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###
