"""empty message

Revision ID: 6813b38c9737
Revises: 
Create Date: 2024-10-30 20:11:31.239010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6813b38c9737'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_logs', sa.Column('event_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event_logs', 'event_url')
    # ### end Alembic commands ###
