"""smoke_add

Revision ID: 6fe2118ac4fc
Revises: 464d225f3785
Create Date: 2024-11-04 23:41:06.987455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fe2118ac4fc'
down_revision = '464d225f3785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cameras_ibfk_1', 'cameras', type_='foreignkey')
    op.create_foreign_key(None, 'cameras', 'users', ['user_id'], ['id'])
    op.add_column('detection_status', sa.Column('smoke_detection_on', sa.Boolean(), nullable=True))
    op.drop_constraint('detection_status_ibfk_1', 'detection_status', type_='foreignkey')
    op.create_foreign_key(None, 'detection_status', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detection_status', type_='foreignkey')
    op.create_foreign_key('detection_status_ibfk_1', 'detection_status', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('detection_status', 'smoke_detection_on')
    op.drop_constraint(None, 'cameras', type_='foreignkey')
    op.create_foreign_key('cameras_ibfk_1', 'cameras', 'users', ['user_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###
