"""emial

Revision ID: 8144e0030408
Revises: 6fe2118ac4fc
Create Date: 2024-11-05 02:45:39.759307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8144e0030408'
down_revision = '6fe2118ac4fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('email', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('email', 'users', ['email'], unique=True)
    # ### end Alembic commands ###
