"""Initial migration

Revision ID: 89b916d46f6c
Revises: 
Create Date: 2024-11-04 07:29:53.440583

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '89b916d46f6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_clips',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('camera_number', sa.Integer(), nullable=False),
    sa.Column('event_name', sa.String(length=50), nullable=False),
    sa.Column('event_url', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('event_logs', 'event_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_logs', sa.Column('event_url', mysql.VARCHAR(length=255), nullable=True))
    op.drop_table('video_clips')
    # ### end Alembic commands ###
